brew "asdf"
brew "bash"
brew "bash-completion"
brew "fzf"
brew "git"
brew "gpg2"
brew "jq"
brew "mas"
brew "nvim"
brew "pinentry-mac"
brew "rpl"
brew "the_silver_searcher"
brew "tmux"
brew "tmuxinator"

tap "homebrew/cask"

cask "1password"
cask "alfred"
cask "deckset"
cask "docker"
cask "firefox"
cask "gpg-suite"
cask "iterm2"
cask "pgadmin4"
cask "secretive"
cask "slate"
cask "spotify"
cask "visual-studio-code"

mas "Bear", id: 1091189122
mas "monday.com", id: 1298450641
mas "Pixelmator Pro", id: 1289583905
mas "Skitch", id: 425955336
mas "The Clock", id: 488764545
mas "Webcam Settings", id: 533696630
